### PR TITLE
Modify front and back end code for search by language

### PR DESCRIPTION
**Pull request by morosebose**
On front end:
- Implement rudimentary search by language feature
- Clean up code for and calls to DialogWindow

On back end:
- Correct language list weirdness for India

### CODE REVIEW

**Comment by morosebose** [comment]
Hiya James! It's not pretty at all but the rudimentary search by language feature works. I ended up making a lot more changes than I expected to a bunch of the front-end code, but surprisingly, the code came out cleaner (removed unnecessary parameters being passed in calls to `DialogWindow()` as well as to `_handleGeneral()` and `handleAreaOrPop()`. I did need to increase the size of `MainWindow()` by 30px to accommodate the new row of buttons. 

I also fixed something that was bothering me about the languages list for India. India has two official languages that parliamentary business can be conducted in (English, Hindi) + 22 "scheduled" languages, which are recognized for such purposes as taking civil service examinations. Hindi is on both those lists, so there's a total of 23 official languages. But the API had a list of only three: English, Hindi, Tamil. I thought that we should either remove Tamil or add the other 20, so I added the other twenty via the back end. 

Since there are so many little changes, I might have introduced bugs. I think I fixed all the ones I noticed, but please do test this code out before merging it. Checkout a branch in git you're not currently working on (from between jk and james). Then do a `git pull origin surajit` into that branch. Then run the back end and front end files and test out the code. If and only if it works as you expect, merge it. 

Next up for me is to change the tkmb.showinfo window to an actual map of the languages.

**Review by jcmkang — CHANGES_REQUESTED** [review]
I was thinking... : 
for the language selection, if the user chooses more than 1 language, maybe we can make error message say.., "please select 1 language?" Because "please make a selection" is a little confusing to me. is it focused on the word "a" as in 1 selection? or asking general to make a selection?

I understand getting rid of the multi, but if we did have the multi we can pass false so that select mode is just single? 

couple options! not 100% sure though. Lmk! 

Should I merge before or should we fix before merge ? lmk on this as well since we had no reasons to not approve and merge for the last pull requests. 

Thanks a bunch!!! 💪🏻

EDIT: (Above was written late in the morning, I might be not understanding functionality correctly)

**Comment by morosebose** [comment]
That's a great catch, James! I didn't even notice that removing `multi` would mean that the user could pick multiple languages in the dialog box. I'm figuring out how to fix this, will take me at least an hour. Expect another commit later today! Thanks for spotting the error and pointing it out.

**Comment by morosebose** [comment]
I think I've fixed all the bugs now! Also, I added a code driver file so that the user can just type `python tour_de_world.py` instead of having to run both the backend and the frontend file. But for our testing we can just continue to use frontend unless we make changes to the backend (which this particular pull request does do).

**Comment by morosebose** [comment]
The code still has a bug in it wrt languages. If the user chooses "English", the resulting info window is so long, it extends off the end of the screen and the user can't see the last few. It's also very hard to close because the "Okay" button is off the screen—user has to hit `Return`. That's ugly UI and UX, but for this PR I think I'm gonna let it slide. I'll create a new issue about the bug. Assign it to me if you want me to work on that, or assign it to yourself if you want to work on it, either is fine. Thanks, James!

**Review by jcmkang — APPROVED** [review]

**Review by jcmkang — CHANGES_REQUESTED** [review]
GOOD AFTERNOON!!! 

I was running the frontend.py and ran into a smalllllll little typo bug error
on line #357, we need to change the column name to `C.population` as it was changed on the backend when making the table. 

Other than that, everything else looks great!! 
- I feel that the project is coming more and more like a little program. ie) we can just run tour_de_world.py too.    .exe (?) maybe coming sooon?? ( I was looking at YT, not sure if that's the way to go..)
- Thank you for re-implementing the single or multiple. I find it funny and smart that you were able to have it decide single or multiple by checking if the desired choice was either continent or language.

**Comment by morosebose** [comment]
Change made! Thanks for catching the omission!

**Pull request merged**
